### ISSUE TITLE
TODO/FIXME Count 4

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-vue-create-organization-wizard#9]
- [ ] TODO: specify propsData
       Commit: (38a932d) Add core files.
       File:  [test/web/10-Wizard.js:16](https://github.com/digitalbazaar/bedrock-vue-create-organization-wizard/blob/master/test/web/10-Wizard.js#L16)
       Dave Longley commented a year ago

  - [ ] TODO: consider moving to `bedrock-karma`?
       Commit: (38a932d) Add core files.
       File:  [test/test.config.js:12](https://github.com/digitalbazaar/bedrock-vue-create-organization-wizard/blob/master/test/test.config.js#L12)
       Dave Longley commented a year ago

  - [ ] FIXME: make configurable
       Commit: (38a932d) Add core files.
       Fi[test/components/index.js:10](https://github.com/digitalbazaar/bedrock-vue-create-organization-wizard/blob/master/test/components/index.js#L10)
       Dave Longley commented a year ago

  - [ ] TODO: $vm.el.something
       Commit: (38a932d) Add core files.
       File:  [test/web/10-Wizard.js:20](https://github.com/digitalbazaar/bedrock-vue-create-organization-wizard/blob/master/test/web/10-Wizard.js#L20)
       Dave Longley commented a year ago

       TODO Count          3
       FIXME Count         1
       Oldest Comment      a year ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: specify propsData
